include $(TOPDIR)/rules.mk

PKG_NAME:=np-{{ community }}
PKG_VERSION:={{ version }}
PKG_RELEASE:={{ release }}

include $(INCLUDE_DIR)/package.mk

{% for profile in profiles %}
define Package/np-{{ community }}-{{ profile["name_sanitized"] }}
  SECTION:=base
  CATEGORY:=Network Profiles
  TITLE:={{ profile["name"] }}
  URL:=https://github.com/libremesh/network-profiles/
  {% if profile["packages"] %}DEPENDS:={{ profile["packages"] }}{% endif %}
endef

define Package/np-{{ community }}-{{ profile["name_sanitized"] }}/description
  Network profile of {{ community }}
  {% if profile["readme"] %}{{ profile["readme"] }}{% endif %}
endef

define Build/Compile
endef

define Build/Configure
endef

define Package/np-{{ community }}-{{ profile["name_sanitized"] }}/install
		$(INSTALL_DIR) $(1)/
		$(CP) ./{{ profile["name"] }} $(1)/
endef
{% endfor %}

{%- for profile in profiles %}
$(eval $(call BuildPackage,np-{{ community }}-{{ profile["name_sanitized"] }})){% endfor -%}
